* URLs
** the lessons
 https://aws.amazon.com/getting-started/use-cases
** S3 home
https://console.aws.amazon.com/s3/home
* internet
** www.example.com is a subdomain of example.com
* for saving money
** "requester pays" is an S3 option

* AWS lingo
** "Route 53" is a ("domain router"?)
** Simple Storage Service = S3 = buckets
*** data can be "queried in place"
*** data can be "selectively retrieved"
with "S3 Select"
*** bucket <=> url
  Each (sub)domain needs its own bucket,
  of the same name.
*** buckets can do versioning
  https://docs.aws.amazon.com/AmazonS3/latest/user-guide/enable-versioning.html
*** use tags to track the cost of a bucket
  thttps://docs.aws.amazon.com/AmazonS3/latest/dev//CostAllocTagging.html
** S3 "Access Points"
Are URLs.
Are to control who can access what.
* website endpoint formatting is weird
A website's endpoing takes one of two almost identical forms,
depending on the region:
  bucket-name.s3-website-region.amazonaws.com
  bucket-name.s3-website.region.amazonaws.com
In my case it's these:
      jefbrown.net.s3-website-us-east-1.amazonaws.com
under.jefbrown.net.s3-website-us-east-1.amazonaws.com
* PITFALL: my domain name is missing an f
* how to make a static website
https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html?refid=gs_card
** PITFALL ! S3 can make websites, but not publish them
S3 lets you make whatever buckets you want,
with any kind of URL-looking name.
And it lets you configure those buckets, if you like,
to serve as websites.

However, until dealing with Route 53,
those URLs *will not resolve*.
Each bucket is associated with an internal "endpoint" like
  http://www.jefbrown.net.s3-website-us-east-1.amazonaws.com
which is available at least to the owner of the account.
Such an internal endpoint can be used to test the content.
If it works, Route 53 can then be used to make the content available from the desired URLs.
** PITFALL: S3 can make buckets for inaccessible URLs
 For instance, if I register jbb-1.net,
 and I make a bucket called jbb1.net,
 I can make the bucket in S3.
 I'll get errors, though,
    when I try to use it as a website in Route 53.
** register a domain
Amazon lets you do that via "Route 53".
It might be possible to use someone else's (cheaper) service.
** make buckets in S3
*** HANDY: To find an S3 bucket's web endpoint
under the bucket, visit properties -> static web hosting
*** for a bucket that hosts content
**** under Properties -> Static Website Hosting
Choose "use as a website".
Type the name of the index document, probably "index.html".
**** under Overview, upload the index
Probably "index.html".
Has to match what was entered under Static Website Hosting.
**** under Permissions
Disable "block public access".
Add a bucket policy allowing (at least) read access.
  See "bucket policy, read only.json"
  in this repo for an example.
  PITFALL: This document must re-state the domain name.
*** TODO for a bucket that redirects to another
**** Name it a subdomain of the registered domain.
**** Configure the redirect
Go to Properties -> Static Website Hosting.
Choose Redirect. Enter the name of the target.
Choose HTTP.
**** TODO under Permissions
Can "block all public access" be on?
Does it need a Bucket Policy?
** route URLs to those buckets in Route 53
Step 3 in the tutorial.
** test
http://jefbrown.net
http://www.jefbrown.net
